### ISSUE TITLE
Can't run this script

### ISSUE THREAD

**Issue by 5up3rc** [faizann24/Fwaf-Machine-Learning-driven-Web-Application-Firewall#3]
When i was test,there are a lot of error codes,Can you submit the code that can run to github？

**Comment by faizann24** [comment]
Please post the error.

**Comment by 5up3rc** [comment]
1.  File "script.py", line 48, in <module>
    bady = [1 for i in range(0,len(tempXssQueries))]  #labels, 1 for malicious and 0 for clean
NameError: name 'tempXssQueries' is not defined
2.Traceback (most recent call last):
  File "script.py", line 42, in <module>
    d = str(urllib.unquote(d).decode('utf8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 11: invalid start byte
3.Traceback (most recent call last):
  File "script.py", line 33, in <module>
    d = str(urllib.unquote(d).decode('utf8'))   #converting url encoded data to simple string
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

run in python 2.7.12
Some syntax errors have been fixed
such as line 45 and no module os

**Comment by SmartAI** [comment]
This problem was solved in my PR #1

**Comment by 5up3rc** [comment]
thank you for your work :-) it's a great project
